FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# Установка дополнительных зависимостей для скрипта
RUN pip install sentence-transformers qdrant-client pandas

COPY src_med/ .
COPY scripts/ ./scripts/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]