apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasource.yaml: |
    apiVersion: 1
    datasource's:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        version: 1
        editable: true