apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'api-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['api-service:8000']
        relabel_configs:
          - source_labels: [__address__]
            target_label: service
            replacement: api-service
          
      - job_name: 'llm-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['llm-service:8000']
        relabel_configs:
          - source_labels: [__address__]
            target_label: service
            replacement: llm-service
        
      - job_name: 'bot-service'
        static_configs:
          - targets: ['bot-service:8000']
        
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-exporter:9308']
