apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot-container
        image: bot-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
        env:
          - name: API_URL
            value: "http://api-service:8000/generate"
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_DB
            value: "telegram_bot_db"
          - name: POSTGRES_USER
            value: "maksimkuznetsov"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegram-secrets
                key: POSTGRES_PASSWORD
          - name: TELEGRAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-secrets
                key: TELEGRAM_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000