name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      zookeeper:
        image: bitnami/zookeeper:3.8
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"

      kafka:
        image: bitnami/kafka:3.7
        env:
          KAFKA_ENABLE_KRAFT: "no"
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
        ports:
          - 9092:9092

    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          **/__pycache__
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (API)
      working-directory: API
      run: |
        pip install -r requirements.txt
        pip install pytest httpx pytest-asyncio pytest-mock

    - name: Run API tests
      working-directory: API
      run: |
        export PYTHONPATH=src_api:$PYTHONPATH  # Замените src_api на вашу папку
        pytest tests/ -v

  test-bot:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          **/__pycache__
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (Bot)
      working-directory: Bot
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-mock

    - name: Run Bot tests
      working-directory: Bot
      run: |
        export PYTHONPATH=src_bot:$PYTHONPATH  # Замените src_bot на вашу папку
        pytest tests/ -v

  test-llm:
    runs-on: ubuntu-latest
    needs: test-bot
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/huggingface
        key: ${{ runner.os }}-huggingface-${{ hashFiles('LLM_text/requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (LLM)
      working-directory: LLM_text
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-mock

    - name: Run LLM tests
      working-directory: LLM_text
      run: |
        export PYTHONPATH=src_llm:$PYTHONPATH  # Замените src_llm на вашу папку
        pytest tests/ -v

  build-docker:
    runs-on: ubuntu-latest
    needs: [test-api, test-bot, test-llm]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    # Будем пушить до tryvia scan, так как Github не даёт достаточно места для загрузки образа
    - name: Build API image
      uses: docker/build-push-action@v4
      with:
        context: API
        push: true
        #load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Bot image
      uses: docker/build-push-action@v4
      with:
        context: Bot
        push: true
        #load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bot-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build LLM image
      uses: docker/build-push-action@v4
      with:
        context: LLM_text
        push: true
        #load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/llm-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build kafka image
      uses: docker/build-push-action@v4
      with:
        context: kafka-broker
        push: true
        #load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kafka-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build postgres image
      uses: docker/build-push-action@v4
      with:
        context: postgres-db
        push: true
        #load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/postgres-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build qdrant image
      uses: docker/build-push-action@v4
      with:
        context: vector-db
        push: true
        #load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/qdrant-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Cache Trivy DB
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.cache/trivy
        key: ${{ runner.os }}-trivy-db

    - name: Scan API image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/api-service:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'
        cache-dir: ${{ github.workspace }}/.cache/trivy
        ignore-unfixed: true

    - name: Scan Bot image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/bot-service:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'
        cache-dir: ${{ github.workspace }}/.cache/trivy
        ignore-unfixed: true

    - name: Scan kafka image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/kafka-service:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'
        cache-dir: ${{ github.workspace }}/.cache/trivy
        ignore-unfixed: true

    - name: Scan LLM image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/llm-service:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'
        cache-dir: ${{ github.workspace }}/.cache/trivy
        ignore-unfixed: true

    - name: Scan postgres image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/postgres-service:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'
        cache-dir: ${{ github.workspace }}/.cache/trivy
        ignore-unfixed: true

    - name: Scan qdrant image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/qdrant-service:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL'
        cache-dir: ${{ github.workspace }}/.cache/trivy
        ignore-unfixed: true

#    - name: Re-login to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#
#    - name: Push API image
#      if: success()
#      run: docker push ${{ secrets.DOCKER_USERNAME }}/api-service:latest
#
#    - name: Push Bot image
#      if: success()
#      run: docker push ${{ secrets.DOCKER_USERNAME }}/bot-service:latest
#
#    - name: Push kafka image
#      if: success()
#      run: docker push ${{ secrets.DOCKER_USERNAME }}/kafka-service:latest
#
#    - name: Push LLM image
#      if: success()
#      run: docker push ${{ secrets.DOCKER_USERNAME }}/llm-service:latest
#
#    - name: Push postgres image
#      if: success()
#      run: docker push ${{ secrets.DOCKER_USERNAME }}/postgres-service:latest
#
#    - name: Push qdrant image
#      if: success()
#      run: docker push ${{ secrets.DOCKER_USERNAME }}/qdrant-service:latest
